# Allows shopware/docs-ci generate_schema workflow to pull required private plugin repos

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/docs-ci:.*
claim_pattern:
  workflow_ref: shopware/docs-ci/.github/workflows/generate_schema\.yml@.*
permissions:
  contents: read

repositories:
  - SwagCommercial
  - SwagCustomizedProducts
  - swagdigitalsalesrooms
